SELECT DISTINCT(CITY) FROM STATION 
WHERE CITY REGEXP '^[aeoui].*$';

-- EXTRA SOLUTION

SELECT CITY FROM STATION 
WHERE CITY LIKE 'a%' OR CITY LIKE 'e%' OR CITY LIKE 'u%' OR CITY LIKE 'i%' OR CITY LIKE 'o%' 